-- ADR 0014 M1.12 (option D): templates become harness-agnostic.
--
-- Pre-M1.12, each `(image_repo, image_tag, harness_pack_uri,
-- snapshot_id)` tuple was its own template row — meaning one bake
-- per (image, harness) pair. The bake-time snapshot captured the
-- microVM with the harness already mounted, so the snapshot was
-- harness-specific.
--
-- M1.12 moves the harness mount from engram-init to bootstrap, and
-- adds `FirecrackerClient::swap_harness_drive` so the warm slot's
-- bake-time stub harness can be swapped for the session's chosen
-- harness ext4 at lease time. The snapshot is now harness-agnostic:
-- one bake per `(image_repo, image_tag)`, served to any harness.
--
-- Make harness_pack_uri nullable, drop it from the unique key, and
-- update the active-lookup index accordingly. The column stays
-- around (nullable) for one release as backwards-compat for rows
-- the M1.11 cascade wrote before option D landed.

ALTER TABLE templates
    ALTER COLUMN harness_pack_uri DROP NOT NULL;

-- Old unique key included harness_pack_uri. Drop it; the column name
-- on the constraint is auto-generated by Postgres at table-create
-- time. Use IF EXISTS so re-running the migration is idempotent.
ALTER TABLE templates
    DROP CONSTRAINT IF EXISTS templates_image_repo_image_tag_harness_pack_uri_snapshot_id_key;

ALTER TABLE templates
    ADD CONSTRAINT templates_image_repo_image_tag_snapshot_id_key
    UNIQUE (image_repo, image_tag, snapshot_id);

-- Active-lookup index: callers ask "active template for (repo, tag)"
-- now; harness is per-session, not per-template.
DROP INDEX IF EXISTS templates_active_lookup;
CREATE INDEX IF NOT EXISTS templates_active_lookup
    ON templates (image_repo, image_tag)
    WHERE active = TRUE;
