/**
 * Orchestrator database schema — ADR 0051 §3/§10.
 *
 * Tables:
 *   - task / task_session: task model (Task 15).
 *   - user / session / account / verification: better-auth core tables (Task 16).
 *     The `user` table carries admin-plugin fields (role, banned, banReason,
 *     banExpires) and the `session` table carries `impersonatedBy` from the
 *     admin plugin.
 *
 * Schema generated via:
 *   bunx --bun @better-auth/cli@latest generate \
 *     --config src/auth/better-auth.ts --output /tmp/better-auth-schema.ts --yes
 * then merged manually below (relations included for completeness; drizzle
 * does not require them for queries but they document the FK graph).
 */

import { relations } from "drizzle-orm";
import {
  pgTable,
  text,
  jsonb,
  timestamp,
  boolean,
  primaryKey,
  index,
} from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// Task model (Task 15)
// ---------------------------------------------------------------------------

export const task = pgTable("task", {
  id: text("id").primaryKey(), // nanoid/uuid
  type: text("type").notNull(), // 'chat' only for now
  title: text("title"),
  status: text("status").notNull().default("open"), // open|working|awaiting_review|done|failed
  createdByUserId: text("created_by_user_id"), // better-auth user id; null = automation (future)
  source: jsonb("source"), // type-specific trigger ref
  workflowRunId: text("workflow_run_id"), // DBOS run — null for chat (ADR §4)
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const taskSession = pgTable(
  "task_session",
  {
    taskId: text("task_id")
      .notNull()
      .references(() => task.id, { onDelete: "cascade" }),
    sessionId: text("session_id").notNull(), // control-plane session id
    role: text("role"), // nullable until multi-session types exist
    // ADR 0052: which profile started this session. Real intra-DB FK (§2).
    // Nullable for pre-feature / out-of-band sessions. Profiles are only ever
    // soft-deleted, so the target always exists; ON DELETE is moot.
    profileId: text("profile_id").references(() => profile.id),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.taskId, t.sessionId] }),
    index("task_session_session_idx").on(t.sessionId), // the authz join (ADR §6) hits this
  ],
);

// ---------------------------------------------------------------------------
// Session profiles (ADR 0052)
//
// Admin-curated session starting points. Orchestrator-only data — the control
// plane never learns about profiles. `image_id` is a LOGICAL ref to the
// coordinator's enabled_images.id (not a DB FK — different tier, ADR §3);
// integrity is enforced in application code. Soft delete only (deleted_at).
// ---------------------------------------------------------------------------

export const profile = pgTable("profile", {
  id: text("id").primaryKey(), // uuid string (crypto.randomUUID())
  name: text("name").notNull(),
  description: text("description").notNull().default(""),
  icon: text("icon").notNull().default("Bot"), // lucide icon name
  imageId: text("image_id").notNull(), // logical ref → enabled_images.id (§3)
  includeUserTokens: boolean("include_user_tokens").notNull().default(false),
  envVars: jsonb("env_vars").notNull().default({}), // { KEY: VALUE }
  // ADR 0055: dynamic skill bundle names this profile's sessions mount (e.g.
  // ["skills", "playwright"]). Resolved by the coordinator to reserved-slot
  // mounts at session create. Empty = base session (no skills).
  skills: jsonb("skills").$type<string[]>().notNull().default([]),
  // ADR 0056: integration capabilities ("provider:action[@resource]") this
  // profile's sessions are granted. Passed to the coordinator at session create
  // (CreateSessionRequest.capabilities), which binds + (later) clamps. Empty =
  // no third-party integration access.
  capabilities: jsonb("capabilities").$type<string[]>().notNull().default([]),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
  deletedAt: timestamp("deleted_at"), // null = active; soft delete only (§4)
});

// ---------------------------------------------------------------------------
// better-auth core tables + admin plugin fields (Task 16)
//
// Generated by: bunx --bun @better-auth/cli@latest generate
// Schema path:  src/auth/better-auth.ts
// ---------------------------------------------------------------------------

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at")
    .$onUpdate(() => new Date())
    .notNull(),
  // admin plugin fields:
  role: text("role"),          // 'admin' | 'user' (we read 'user' as "member")
  banned: boolean("banned").default(false),
  banReason: text("ban_reason"),
  banExpires: timestamp("ban_expires"),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    // admin plugin field:
    impersonatedBy: text("impersonated_by"),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

// ---------------------------------------------------------------------------
// User session secrets — KEK-envelope sealed at rest (ADR 0051 Drip A)
//
// A generic, env-var-name-keyed per-user secret store. The orchestrator OWNS
// the user's harness identity secrets (today just the Claude
// CLAUDE_CODE_OAUTH_TOKEN) here in its own Postgres, next to the users they
// belong to, replacing the coordinator's per-user sealed SecretService vault.
// At session-create the orchestrator opens all of a user's secrets and passes
// them to the control plane via CreateSession.harness_env; the coordinator
// injects + persists them so they replay on resume.
//
// At-rest posture: every value is KEK-envelope SEALED with the SAME key + SAME
// envelope format as the Rust coordinator (engram-crypto / ENGRAM_KEK_MASTER_KEY)
// — see src/crypto/seal.ts. The row holds ciphertext only; the master key lives
// outside the DB (env var, sourced from GCP Secret Manager in prod). A read of
// the row alone does not yield plaintext. wrapped_dek / nonce / ciphertext are
// stored as base64 `text` (simplest in drizzle/Bun). Plaintext is NEVER logged.
// ---------------------------------------------------------------------------

export const userSessionSecrets = pgTable(
  "user_session_secrets",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    // e.g. "CLAUDE_CODE_OAUTH_TOKEN" — the harness env var this secret feeds.
    envVarName: text("env_var_name").notNull(),
    // KEK-envelope sealed columns (base64 text). Mirrors engram-crypto SealedCred.
    wrappedDek: text("wrapped_dek").notNull(),
    nonce: text("nonce").notNull(),
    ciphertext: text("ciphertext").notNull(),
    keyId: text("key_id").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at")
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [primaryKey({ columns: [t.userId, t.envVarName] })],
);

// ---------------------------------------------------------------------------
// Relations (informational — drizzle does not require these for queries)
// ---------------------------------------------------------------------------

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));
