export {
  encodedSpecBlockCacheSize,
  isSpecBlockKind,
  matchingSpecBlockCachedRender,
  readSpecBlockAttrs,
  semanticSpecNodeJson,
  SPEC_BLOCK_CACHE_MAX_BYTES,
  SPEC_BLOCK_KINDS,
  SPEC_BLOCK_RENDERER_REVISION,
  SPEC_RENDER_TARGETS,
  specBlockRegistration,
  specBlockRegistry,
  specRenderTargetRegistration,
  specNodesSemanticallyEqual,
  validateSpecBlockCachedRender,
  type SpecBlockAttrs,
  type SpecBlockCachedRender,
  type SpecBlockExportMode,
  type SpecBlockKind,
  type SpecBlockProvenance,
  type SpecBlockRegistration,
  type SpecRenderTarget,
  type SpecRenderTargetRegistration,
} from "./blocks.ts";
export {
  isSpecTradeoffSign,
  renderAlternativesConsidered,
  SPEC_ALTERNATIVES_MAX_OPTIONS,
  SPEC_ALTERNATIVES_MIN_OPTIONS,
  SPEC_ALTERNATIVES_TRADEOFF_COUNT,
  SPEC_TRADEOFF_SIGNS,
  SpecAlternativesError,
  validateSpecAlternatives,
  type AlternativesDecidedTranscriptChip,
  type AlternativesProposedTranscriptChip,
  type SpecAlternativeOption,
  type SpecAlternativeTradeoff,
  type SpecAlternativesComparison,
  type SpecAlternativesComparisonCell,
  type SpecAlternativesComparisonRow,
  type SpecAlternativesProposal,
  type SpecAlternativesStage,
  type SpecAlternativesTranscriptChip,
  type SpecTradeoffSign,
} from "./alternatives.ts";
export {
  createSectionRelativeAnchor,
  isRangeInSectionBody,
  parseSectionRelativeAnchor,
  resolveSectionRelativeAnchor,
  serializeSectionRelativeAnchor,
  type SectionRelativeAnchor,
} from "./anchors.ts";
export {
  findQuestionMarker,
  insertQuestionMarker,
  QuestionResolutionConflictError,
  removeQuestionMarker,
  resolveQuestionMarker,
  type LocatedQuestionMarker,
  type ResolveQuestionMarkerResult,
} from "./questions.ts";
export {
  type RestoreSectionStateUndo,
  type SectionState,
  type SectionStateTranscriptChip,
  type SectionStateValue,
  type SpecSelectionAction,
  type SpecSelectionActionPayload,
  type SpecSelectionSpan,
  type SpecTranscriptChip,
  type TrackedEditTranscriptChip,
  selectionSliceFingerprint,
} from "./actions.ts";
export {
  extractRequirementDefinitions,
  extractRequirementReferences,
  RequirementLedger,
  RequirementIntegrityError,
  validateRequirementEdit,
  type RequirementDefinition,
  type RequirementDocumentLike,
  type RequirementId,
  type RequirementKind,
  type RequirementPrefix,
  type RequirementReference,
} from "./requirements.ts";
export {
  SPEC_FRAGMENT_NAME,
  createTemplateDocument,
  findSection,
  parseMarkdownBlocks,
  parseMarkdown,
  renderMarkdown,
  replaceSection,
  schema,
  specNodeSpecs,
  type SpecTemplate,
  type SpecTemplateSection,
} from "./schema.ts";
