export {
  encodedSpecBlockCacheSize,
  isSpecBlockKind,
  matchingSpecBlockCachedRender,
  readSpecBlockAttrs,
  semanticSpecNodeJson,
  SPEC_BLOCK_CACHE_MAX_BYTES,
  SPEC_BLOCK_KINDS,
  SPEC_BLOCK_RENDERER_REVISION,
  SPEC_RENDER_TARGETS,
  specBlockRegistration,
  specBlockRegistry,
  specRenderTargetRegistration,
  specNodesSemanticallyEqual,
  validateSpecBlockCachedRender,
  type SpecBlockAttrs,
  type SpecBlockCachedRender,
  type SpecBlockExportMode,
  type SpecBlockKind,
  type SpecBlockProvenance,
  type SpecBlockRegistration,
  type SpecRenderTarget,
  type SpecRenderTargetRegistration,
} from "./blocks.ts";
export {
  createSectionRelativeAnchor,
  isRangeInSectionBody,
  parseSectionRelativeAnchor,
  resolveSectionRelativeAnchor,
  serializeSectionRelativeAnchor,
  type SectionRelativeAnchor,
} from "./anchors.ts";
export {
  findQuestionMarker,
  insertQuestionMarker,
  QuestionResolutionConflictError,
  removeQuestionMarker,
  resolveQuestionMarker,
  type LocatedQuestionMarker,
  type ResolveQuestionMarkerResult,
} from "./questions.ts";
export {
  type RestoreSectionStateUndo,
  type SectionState,
  type SectionStateTranscriptChip,
  type SectionStateValue,
  type SpecSelectionAction,
  type SpecSelectionActionPayload,
  type SpecSelectionSpan,
  type SpecTranscriptChip,
  type TrackedEditTranscriptChip,
  selectionSliceFingerprint,
} from "./actions.ts";
export {
  extractRequirementDefinitions,
  extractRequirementReferences,
  RequirementLedger,
  RequirementIntegrityError,
  validateRequirementEdit,
  type RequirementDefinition,
  type RequirementDocumentLike,
  type RequirementId,
  type RequirementKind,
  type RequirementPrefix,
  type RequirementReference,
} from "./requirements.ts";
export {
  analyzeTraceability,
  applyOutsideIn,
  REQUIREMENTS_SECTION_KEY,
  SUBSTANTIVE_BLOCK_MIN_CHARS,
  TraceabilityInputError,
  type GapFinding,
  type GapFindingKind,
  type GapFindingSeverity,
  type GapProposedDiff,
  type OutsideInResult,
  type TraceabilityBlock,
  type TraceabilityCitation,
  type TraceabilityInput,
  type TraceabilityLayer,
  type TraceabilityMatrix,
  type TraceabilityMatrixCell,
  type TraceabilityMatrixRow,
  type TraceabilityResult,
  type TraceabilitySection,
  type TraceabilitySectionState,
  type TraceabilityVerdict,
} from "./traceability.ts";
export {
  SPEC_FRAGMENT_NAME,
  createTemplateDocument,
  findSection,
  parseMarkdownBlocks,
  parseMarkdown,
  renderMarkdown,
  replaceSection,
  schema,
  specNodeSpecs,
  type SpecTemplate,
  type SpecTemplateSection,
} from "./schema.ts";
